@startuml get-movie-data-diagram

title MovieInfoAPI

skinparam BoxPadding 50

boundary PrimaryWebsite
boundary ApiGateway
participant GetMoviesLambda
participant GetMovieLambda
participant SSM
database DynamoDB
participant LexiconDigital

== Movie List ==
PrimaryWebsite -> ApiGateway : <b>GET</b> <i>/movies</i>
ApiGateway -> GetMoviesLambda : <b>GET</b> <i>/movies</i>

activate GetMoviesLambda #LightGreen
group MoviesHandler
    GetMoviesLambda -> SSM : Get Parameters <i>[TableName, MovieEndpoint, MovieEndpointApiKey]</i>
    activate SSM #LightGreen
    GetMoviesLambda <- SSM : Values
    deactivate SSM

    GetMoviesLambda -> LexiconDigital : <b>GET</b> <i>/{provider}/movies</i>
    activate LexiconDigital #LightGreen
    alt Success
        GetMoviesLambda <- LexiconDigital : <b>200</b> <i>[movies...]</i>
    else Failure
        GetMoviesLambda <- LexiconDigital : <b>4XX | 5XX</b> <i>error-message</i>
        GetMoviesLambda -> DynamoDB : **<< Get(TableName, POST body) >>**
        activate DynamoDB #LightGreen
        alt Success
            GetMoviesLambda <- DynamoDB : **<< Success >>**
        else Failure
            GetMoviesLambda <- DynamoDB : Failure: <i>error-code, error-message</i>
        end
        deactivate DynamoDB
    end
    deactivate LexiconDigital
end

ApiGateway <- GetMoviesLambda : HTTP Response [Success 200 | Failure 4XX/5XX]
deactivate GetMoviesLambda

== Movie Details ==

PrimaryWebsite -> ApiGateway : <b>GET</b> <i>/movie?movieID={movieId}</i>
ApiGateway -> GetMoviesLambda : <b>GET</b>

activate GetMoviesLambda #LightGreen
group MovieHandler
    GetMoviesLambda -> SSM : Get Parameters TableName, MovieEndpoint, MovieEndpointApiKey
    activate SSM #LightGreen
    GetMoviesLambda <- SSM : Values
    deactivate SSM

    GetMoviesLambda -> DynamoDB : **<< Get(TableName, POST body) >>**
    activate DynamoDB #LightGreen
    alt Success
        GetMoviesLambda <- DynamoDB : **<< Success >>**
    else Failure
        GetMoviesLambda <- DynamoDB : **<< Failure: [error-code, error-message] >>**
    end
    deactivate DynamoDB
end
ApiGateway <- GetMoviesLambda : HTTP Response [Success <b>200</b> | Failure 4XX/5XX]
deactivate GetMoviesLambda

@enduml