@startuml sequence-diagram

title MovieInfoAPI

skinparam BoxPadding 50

boundary PrimaryWebsite
boundary ApiGateway
participant GetMoviesLambda
participant GetMovieLambda
participant SSM
database DynamoDB
participant LexiconDigital

note right of ApiGateway 
**API Gateway** All requests routed via API Gateway
end note

== Movie List ==
PrimaryWebsite -> GetMoviesLambda : <b>GET</b> <i>/movies</i>
activate ApiGateway #LightGray
activate GetMoviesLambda #LightGreen
group MoviesHandler
    GetMoviesLambda -> SSM : **GET** Parameters <i>[Endpoint, ApiKey, TableName, Providers]</i>
    activate SSM #LightGreen
    GetMoviesLambda <- SSM : <i>[Configuration parameter values]</i>
    deactivate SSM

    GetMoviesLambda -> LexiconDigital : <b>GET</b> <i>/{provider}/movies</i>
    activate LexiconDigital #LightGreen
    alt Success
        GetMoviesLambda <- LexiconDigital : <b>200</b> <i>[movies...]</i>
        GetMoviesLambda -> DynamoDB : Cache the results
    else Failure
        GetMoviesLambda <- LexiconDigital : <b>4XX | 5XX</b> <i>error-message</i>
        GetMoviesLambda -> DynamoDB : **<< Read cached results >>**
        activate DynamoDB #LightGreen
        alt Success
            GetMoviesLambda <- DynamoDB : **<< Success >>** <i>[movie list]</i>
        else Failure
            GetMoviesLambda <- DynamoDB : **<< Failure >>** <i>error-code, error-message</i>
        end
        deactivate DynamoDB
    end
    deactivate LexiconDigital
end
PrimaryWebsite <- GetMoviesLambda : HTTP Response [**Success 200** [Body: MovieList] | **Failure 4XX/5XX **]
deactivate GetMoviesLambda
deactivate ApiGateway

== Movie Details ==

PrimaryWebsite -> GetMovieLambda : **GET** <i>/movie?movieID={movieId}</i>
activate ApiGateway #LightGray

activate GetMovieLambda #LightGreen
group MovieHandler
    GetMovieLambda -> SSM : **GET** Parameters <i>[Endpoint, ApiKey, TableName, Providers]</i>
    activate SSM #LightGreen
    GetMovieLambda <- SSM : <i>[Configuration parameter values]</i>
    deactivate SSM

    GetMovieLambda -> LexiconDigital : <b>GET</b> <i>/{provider}/movie?movieID={movieId}
    alt Success
        GetMovieLambda <- LexiconDigital : <b>200</b> <i>[movies...]</i>
        GetMovieLambda -> DynamoDB : Cache the results
    else Failure
        GetMovieLambda <- LexiconDigital : <b>4XX | 5XX</b> <i>error-message</i>
        GetMovieLambda -> DynamoDB : **<< Read cached results >>**
        activate DynamoDB #LightGreen
        alt Success
            GetMovieLambda <- DynamoDB : **<< Success >>** <i>[details for {movieID}]</i>
        else Failure
            GetMovieLambda <- DynamoDB : **<< Failure >>** <i>error-code, error-message</i>
        end
        deactivate DynamoDB
    end
end
PrimaryWebsite <- GetMovieLambda : HTTP Response [**Success 200** [Body: Movie Pricing] | **Failure 4XX/5XX]**
deactivate GetMovieLambda

@enduml